---
title: "Bootstrapping"
output: github_document
---



```{r}
library(tidyverse)
library(p8105.datasets)
library(modelr)
set.seed(1)
```

# Generate a relevant example 
```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1,1),
    error = rnorm(n_samp,0,1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst = 
  sim_df_const |>
  mutate(error = error *.75 *x,
         y = 2 + 3 *x + error)

sim_df_const|>
  ggplot(aes(x = x, y = y)) + geom_point()
```


fit some linear models

```{r}
sim_df_const|>
  lm(y ~ x, data = _)|>
  broom::tidy()|>
  knitr::kable(digits = 3)

sim_df_nonconst|>
  lm(y ~ x, data = _)|>
  broom::tidy()|>
  knitr::kable(digits = 3)
```


## Draw and analyze a bootstrap sample

start with a lil function

```{r}
boot_sample = function(df){
  
  sample_frac(df, replace = TRUE)
  
}
```

lets see how this work

```{r}
sim_df_nonconst|>
  boot_sample()|>
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5)+
  stat_smooth(method = "lm")
```

## Draw a lot of samples and analyze them
```{r}
boot_straps = 
  tibble(strap_number = 1:2500)|>
  mutate(strap_sample = map(strap_number, \(i) boot_sample(sim_df_nonconst)))

boot_straps|>
  pull(strap_sample)|>
  nth(1)|>
  arrange(x)
```


now do the `lm` fit

```{r}
boot_results = 
  boot_straps|>
  mutate(
    models = map(strap_sample, \(df) lm(y~x, data = df)),
    result = map(models, broom::tidy)
  )|>
  select(strap_number, result)|>
  unnest(result)
    
```

try to summarize these results -- get a bootstrap SE

```{r}
boot_results|>
  group_by(term)|>
  summarise(
    sd = sd(estimate)
  )
```

look at distribution
```{r}
boot_results|>
  filter(term =="x")|>
  ggplot(aes(x = estimate)) +
  geom_density()
```

can I construct a CI

```{r}
boot_results |> 
  group_by(term) |> 
  summarize(
    ci_lower = quantile(estimate, 0.025), 
    ci_upper = quantile(estimate, 0.975))
```


