---
title: "linear_model"
author: "Tianyou He"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(modelr)
```
## Load and clean the Airbnb data
```{r}
data("nyc_airbnb")
```

```{r}
nyc_airbnb = 
  nyc_airbnb |>
  mutate(stars = review_scores_location /2)|>
  select(
    price, stars, borough = neighbourhood_group, neighbourhood, room_type
  )|>
  filter(borough != "Staten Island")
```

lets fit the linear model

```{r}
fit = 
  nyc_airbnb|>
  lm(price ~ stars + borough, data = _)
fit
```
look at fit
```{r}
fit
summary(fit)
summary(fit)$coef
coef(fit)
## fitted.values(fit)
```

tidy up the output

```{r}
fit |> 
  broom::tidy() |> 
  select(term, estimate, p.value) |> 
  mutate(term = str_replace(term, "^borough", "Borough: ")) |> 
  knitr::kable(digits = 3)
```

```{r}
fit = 
  nyc_airbnb|>
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  )|>
  lm(price ~ stars + borough + room_type, data = _)

fit|>
  broom::tidy()
```


## quick look at diagnostis

```{r}
modelr::add_residuals(nyc_airbnb, fit)
modelr::add_predictions(nyc_airbnb, fit)
```
```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = stars, y = resid)) + geom_point()
```
```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = borough, y = resid)) + geom_violin()
```

## Hypothesis test for categorical predictor

```{r}
fit|>
  broom::tidy()
```

```{r}
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alternative = lm(price ~ stars + borough + room_type, data = nyc_airbnb)

anova(fit_null, fit_alternative)|>
  broom::tidy()
```

## Borough-level differences 

```{r}
fit = 
  nyc_airbnb|>
  lm(price = stars*borough + room_type*borough, data = _)

fit|>
  broom::tidy()
```

```{r}
airbnb_lm = function(df){
  lm(price ~ stars + room_type, data = df)
}

nyc_airbnb|>
  nest(df = -borough)|>
  mutate(models = map(df, airbnb_lm),
         results = map(models, broom::tidy))|>
  select(borough, results)|>
  unnest(results)|>
  select(borough, term, estimate)|>
  pivot_wider(
    names_from = term,
    values_from = estimate
  )|>
  knitr::kable(digits = 2)
```

## binary outcome (去看课件，这个data set mac上下载有问题)




